### ISSUE TITLE
Small camelcase issue in filename.

### ISSUE THREAD

**Issue by ChrisHagg** [hiddeco/transip#11]
There seems to be a small camelcase issue with a filename:

transip/src/Model/Webhost.php

I believe this should be:
transip/src/Model/WebHost.php (uppercase H)

No problems with my local development environment (Laravel Homestead), it throws errors however on my server environment.

Hope this helps, thank you for your effort.

**Comment by hiddeco** [comment]
@ChrisHagg thanks for the issue report, and my apologies for the late response. Can you provide more details about the errors you are experiencing on your server environment?

Looking at the [official 'client'](https://api.transip.nl/downloads/transapi_transip.nl_v5_6.tar.gz) I believe you are correct, however I'd like to be able to verify the fix before releasing a new version.

**Comment by ChrisHagg** [comment]
@hiddeco It seems unable to find the correct file due to the camelcase difference:

PHP Fatal error:  Class 'TransIP\Model\WebHost' not found in [server path]/vendor/hiddeco/transip/src/Api/AbstractApi.php on line 36

In AbstractApi.php line 36:

Class 'TransIP\Model\WebHost' not found

When I change the filename as described above the problem is solved.

**Comment by hiddeco** [comment]
@ChrisHagg there was indeed a CamelCase issue due to a typo in one of the class maps. I modified the class name and the FQCNs are now resolved through the `::class` constant which should make it a bit harder to have these kind of bugs in the future. 

Bugfix is available in the `5.6` release I just published. Thanks again for the issue report!
